### ISSUE TITLE
Error 500 when connect with mixer chat

### ISSUE THREAD

**Issue by trunght-afkvr** [mixer/client-node#71]
In the last few days, I have this errors on my server

Error: unexpected server response (500)
    at ClientRequest._req.on (/home/ubuntu/boombot-server/node_modules/ws/lib/WebSocket.js:642:26)
    **at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)

Sometimes I even have this error:

Error: unexpected server response (525)
    at ClientRequest._req.on (/home/ubuntu/boombot-server/node_modules/ws/lib/WebSocket.js:642:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)

**Comment by Firebottle** [comment]
We're seeing this same error in Firebot. It only occurs when the initial connect happens, and even then it only happens sometimes. Might be related to a certain endpoint or something.

**Comment by SimonSchick** [comment]
525 appears to be related to cloudflare, we are working with them to resolve this issue.
I'm looking into the other errors.

**Comment by Firebottle** [comment]
If it helps, I tried connecting about 30 times and logged the chat endpoint it was connecting to. Not a solid fair count since it chooses at random, but here are the endpoints I was seeing the problem on most. The first number is the wss://chatX number, the second is how many times I got a 500 error in my attempts.

1 - 0
2 - 1
3 - 0
4 - 0
5 - 0
6 - 1
7 - 0
8 - 4
9 - 3

**Comment by nickangelou** [comment]
Receiving the same errors on my side as well. From what I could gather, this code uses a very old version of the `ws` library and maybe some errors in handling connection state are because of this.

**Comment by ProbablePrime** [comment]
Closing as very old, if you still have 500s please re-open
